theme: jekyll-theme-minimal
title: Welcome to Wasim's page
<a href="https://github.com/CS499WasimAlim/Capstone/blob/f47a3b2f7259c00dfff76ab31c83b74352ec4bac/main2.c#L12-L14">
description: Initial page

